### ISSUE TITLE
raw()-queries require id=MultiFieldPK() to be after all other fields

### ISSUE THREAD

**Issue by soulne4ny** [simone/django-compositekey#11]
Hi!

Using model.object.raw() I've got to the case when model instance fields don't match db tables fields.

`RawQuerySet.__iter__` requires primary key fields to be in the cursor ( https://github.com/django/django/blob/stable/1.4.x/django/db/models/query.py#L1480 ), that's why I've added fake `id` value like

``` SQL
SELECT 'fake' id, * FROM ...
```

As a result I've got values in the model shifted.  I've tried to move fake `id` after `*`, but that didn't help.  Digging where it fails I've found that it happens in `patched_model_init` as it expects `args` matching `_meta.db_fields` not true `_meta.fields`.

It could be solved moving `id = MultiFieldPK(...)` after all the value fields.  But I suspect it won't solve the problem in case of model inheritance.

I've added tests for the case. https://github.com/soulne4ny/django-compositekey/tree/master/testprj/composite_raw/.

I've tried to make a patch, but it does not work.

**Comment by simone** [comment]
Thanks soulne4ny,
I've change the RawQuerySet in the sqlconcat active branch.

No sense the required of the PK in RawQuery when the pk is composite.
Now, the fake id is completly ignored, so is ok use the mpk definition before and after. 

see my commit here, I ave added some tests.
I prefer insert in the djangotests suits, instead testprj

https://github.com/simone/django-compositekey/commit/eb8a4c66db2493c7b46bd6a7df7916e96fd2d520

**Comment by soulne4ny** [comment]
On 30.06.2012 11:19, Simone Federici wrote:

> Thanks soulne4ny,
> I've change the RawQuerySet in the sqlconcat active branch.
> 
> No sense the required of the PK in RawQuery when the pk is composite.
> Now, the fake id is completly ignored, so is ok use the mpk definition before and after.

Thank you Simone!  It works for us :)

## 

Alex
