### ISSUE TITLE
Django v1.5 - ImportError: cannot import name LHS_JOIN_COL

### ISSUE THREAD

**Issue by lowaa** [simone/django-compositekey#19]
This breaks compatibility with django 1.5.

In compositekey/db/models/sql/query.py:

from django.db.models.sql.constants import LHS_JOIN_COL, RHS_JOIN_COL, LOOKUP_SEP, LHS_ALIAS

In django 1.5, the constants.py file no longer has the values that we are trying to import. The constants in question are used for tuple lookups.

**Comment by simone** [comment]
Yes thanks,
I have to branch the 1.5 version, there are many changes in Django 1.5 I have to check.

**Comment by simone** [comment]
This error is fixed.

**Comment by lowaa** [comment]
Thanks!
