### ISSUE TITLE
Naive assumption of "quote" function and "||" operator existence and behavour?

### ISSUE THREAD

**Issue by francescortiz** [simone/django-compositekey#23]
The class "UseConcat" assumes:

```
concat = "||"
cq = "quote(%s%s)" # if the value is not an int sorround it with quotes
```

but it is not true for all database backends. In my case, SQL server, I had to use

```
concat = "+"
cq = "cast(%s%s as nvarchar(4000))" # never adds quotes
```

which also implies using direct string casting instead of "self.quote_v" in the following line (around 67), because SQL server does not add quotes when casting to string:

```
params = [SEPARATOR.join([self.quote_v(v) for v in val]) for val in self.values]
```

**Comment by simone** [comment]
Very cool,
so you want add the MS SQL Server support.

Yes, UseConcat is an abstraction that can be overrided
in the end of the module there are the implementations for these 5 databases

service["sqlite"] = UseConcat
service["postgresql"] = UseConcatQuote
service["mysql"] = UseTupleWithDummy
service["oracle"] = UseTuple
service["DB2"] = UseTupleValues

**Comment by francescortiz** [comment]
Great! I'll be implementing this ASAP.

**Comment by simone** [comment]
merged!
