### ISSUE TITLE
please can you put in https://pypi.python.org/pypi/django-compositekey the last version of branch 1.4.x ??

### ISSUE THREAD

**Issue by epineda** [simone/django-compositekey#24]
thank you!!!!!

I had problems with old 0.1-alpha version and oracle backend... but was solved with the last version of 1.4.x branch...

"("Trying to 'quote' a multiple key FIELD. Operation not supported yet. Please fix it..."

**Comment by simone** [comment]
https://pypi.python.org/pypi/django-compositekey/1.4.0
thank you for the reminder
