### ISSUE TITLE
quantize result has too many digits for current context

### ISSUE THREAD

**Issue by mwuhid1** [simone/django-compositekey#34]
Hello,
I'm using django-compositekey (id = db.MultiFieldPK("field1", "field2", "field3")) on an oracle remote database created with inspectdb. It is successful on some tables but there is a table which returns this error : "quantize result has too many digits for current context". Note that field1 is Charfield and field2 and 3 are IntegerField. My django version is 1.5.
Can somebody help me?

**Comment by simone** [comment]
It looks like a problem with a models.DecimalField, are you sere there are no other field on your table?
