### ISSUE TITLE
ImportError: cannot import name EmptyShortCircuit

### ISSUE THREAD

**Issue by mwuhid1** [simone/django-compositekey#36]
Hello,
I am trying to use django-compositekey on django 1.9 project and it is giving me this error: "ImportError: cannot import name EmptyShortCircuit". What can I do about it. Please help me.

**Comment by dmytrokyrychuk** [comment]
I don't think django-compositekey supports Django 1.9. Older django-compositekey versions supported Django 1.4 and 1.5.

**Comment by simone** [comment]
django-compositekey supports only Django 1.4 and 1.5.
