### ISSUE TITLE
C

### ISSUE THREAD

**Issue by LensHunnel** [simone/django-compositekey#37]
Hi,
I wonder if there is a way to use django-compositekey with Contenttype to define generics objects.
Thanks

**Comment by simone** [comment]
forget this project was developed for django 1.2 and moved till 1.5 but without a production under last version
Actually django moved so foreward that this project has no chance to be mantained.
By the way. yes I was starting to develop also the generic related objects using the couple content type id and pk but i never finished that part. 
best luck.
