### ISSUE TITLE
Urgent Help: Trying to implement composite Primary Key - Got Below Error

### ISSUE THREAD

**Issue by REMALAMANOJ** [simone/django-compositekey#38]
Dear Team,

Hope you all doing Well!
In my project, i am using 'django-compositekey-1.5.0'.

Model.py:
--------------
class Book(models.Model):
    id = db.MultiFieldPK("name", "author")
    name = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    publisher = models.CharField(max_length=25)

    class Meta:
        ordering = ('name', 'author')

    def __unicode__(self):
        return u"%s %s" % (self.name, self.author)
    

Got Below Error:
  File "C:\Users\manoj.remala\AppData\Local\Programs\Python\Python37-32\lib\site-packages\compositekey\db\models\fields\wrap.py", line 49
    if len(values) <> len(fields):
                    ^
SyntaxError: invalid syntax

(venv1) C:\Users\manoj.remala\PycharmProjects\MANOJ_IVY\IVYFSSWeb\IVYFSS>

Note: I have changed not equal symbol '<>' to '!='

Now, got a new issue
File "C:\Users\manoj.remala\AppData\Local\Programs\Python\Python37-32\lib\site-packages\compositekey\db\models\base.py", line 8, in <module>
    from itertools import izip
ImportError: cannot import name 'izip' from 'itertools' (unknown location)

Could not able to figure it out. Could you please help.

Thanks
Manoj R

**Comment by simone** [comment]
Was developed in python 2.7

In any case, it’s very old library, no support at all.
Best




Il giorno mar 2 giu 2020 alle 10:36 REMALAMANOJ <notifications@github.com>
ha scritto:

**Comment by REMALAMANOJ** [comment]
Dear Simone,

Thanks for your update.
Currently I am using python 3.7 in my project. Could you please suggest how can I implement the composite primary key.

Your help would be much appreciated.

Best Regards
Manoj

**Comment by simone** [comment]
Have you tried this library? seem to be maintained and it supports
Python 2.7, 3.4, 3.5, 3.6, 3.7
Django 1.11, 2.0, 2.1
 
https://pypi.org/project/django-composite-foreignkey/

I didn't try the library but it has  43 stars and 13 forks on github
